version: '3'
services:
  app:
    container_name: nextcloud
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - ./nextcloud:/var/www/html
  office:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/log:/var/log/onlyoffice
  nginx:
    container_name: nginx
    image: nginx:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud:/var/www/html
      - ./cert:/cert
  db:
    container_name: mariadb
    image: mariadb:10.2
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    #ports:
      #- 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: nextcloud_usr
      MYSQL_PASSWORD: DBP@ssword
    volumes:
      - ./db:/var/lib/mysql
volumes:
  onlyoffice:
  nextcloud:
  cert:
  mysql_data:
